### ISSUE TITLE
efivar build error on FC25 with GCC 6.3.1

### ISSUE THREAD

**Issue by yunguowei** [WindRiver-OpenSourceLabs/meta-secure-env#34]
see log.do_install:

DEBUG: Executing shell function do_install
NOTE: make -j 24 -e MAKEFLAGS= DESTDIR=/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/efivar-native/0.21-r0/image install
make[1]: Entering directory '/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/efivar-native/0.21-r0/git/src'
gcc  -isystem/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/sysroots/x86_64-linux/usr/include -O2 -pipe -std=gnu99 -Werror -Wall -Wsign-compa
re -Wstrict-aliasing -fshort-wchar -fPIC -fvisibility=hidden -D_GNU_SOURCE -I/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux
/efivar-native/0.21-r0/git/src/include/efivar/   -isystem/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/sysroots/x86_64-linux/usr/include -c 
-o vars.o vars.c
vars.c: In function 'is_64bit':
vars.c:132:3: error: 'readdir_r' is deprecated [-Werror=deprecated-declarations]
   int rc = readdir_r(dir, &entry, &result);
   ^~~
In file included from vars.c:18:0:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
cc1: all warnings being treated as errors
/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/efivar-native/0.21-r0/git/Make.rules:17: recipe for target 'vars.o' failed
make[1]: *** [vars.o] Error 1
make[1]: Leaving directory '/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/efivar-native/0.21-r0/git/src'
Makefile:20: recipe for target 'install' failed
make: *** [install] Error 2
ERROR: oe_runmake failed
ERROR: Function failed: do_install (log file is located at /buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/efivar-native/0.21-r0/temp/log.do_install.27978)

No such issue on ubuntu1404/1604/centos7

**Comment by lifupan** [comment]
fixed by
https://github.com/WindRiver-OpenSourceLabs/meta-secure-env/commit/7dd862aed4b1740e462bfa99eec6e0ee9064771a
